require 'rubygems'
require 'hoe'
include FileUtils
require File.join(File.dirname(__FILE__), 'lib', 'caldav', 'version')

AUTHOR = "brandon"  # can also be an array of Authors
EMAIL = "your contact email for bug fixes and info"
DESCRIPTION = "description of gem"
GEM_NAME = "caldav" # what ppl will type to install your gem
RUBYFORGE_PROJECT = "caldav" # The unix name for your project
HOMEPATH = "http://#{RUBYFORGE_PROJECT}.rubyforge.org"
RELEASE_TYPES = %w( gem ) # can use: gem, tar, zip
#CLEAN = %w()


NAME = "caldav"
REV = nil # UNCOMMENT IF REQUIRED: File.read(".svn/entries")[/committed-rev="(d+)"/, 1] rescue nil
VERS = ENV['VERSION'] || (Caldav::VERSION::STRING + (REV ? ".#{REV}" : ""))
#CLEAN.include ['**/.*.sw?', '*.gem', '.config']
RDOC_OPTS = ['--quiet', '--title', "caldav documentation",
    "--opname", "index.html",
    "--line-numbers", 
    "--main", "README",
    "--inline-source"]

# Generate all the Rake tasks
# Run 'rake -T' to see list of generated tasks (from gem root directory)
hoe = Hoe.new(GEM_NAME, VERS) do |p|
  p.author = AUTHOR 
  p.description = DESCRIPTION
  p.email = EMAIL
  p.summary = DESCRIPTION
  p.url = HOMEPATH
  p.rubyforge_name = RUBYFORGE_PROJECT if RUBYFORGE_PROJECT
  p.test_globs = ["test/**/*_test.rb"]
#  p.clean_globs = CLEAN  #An array of file patterns to delete on clean.
  
  # == Optional
  #p.changes        - A description of the release's latest changes.
  #p.extra_deps     - An array of rubygem dependencies.
  #p.spec_extras    - A hash of extra values to set in the gemspec.
  p.extra_deps << ['activesupport', 'tzinfo', 'builder']
  
end
          